### PR TITLE
feat: add repo network deps path

### PR DESCRIPTION
**Pull request by izayl**
add three network deps graph related url

### CODE REVIEW

**Comment by fregante** [comment]
Thank you for the PR. Where are you planning to use these? We generally don't add detections unless they're confirmed in Refined GitHub first

**Comment by fregante** [comment]
> I'm planing to add useful-dependents feature to Refined Github

It's best to discuss features before sending PRs. Given the [result](https://useful-dependents.vercel.app/?repo=https://github.com/facebook/react) of one of the demos on your homepage, I'm going to decline

Screenshot 15

The website looks good however 👍

**Comment by izayl** [comment]
@fregante where should I proposal new feature?

about the [unhelpful results](https://useful-dependents.vercel.app/?repo=https://github.com/facebook/react), it just the bad implement of GitHub, if you visit the https://github.com/facebook/react/network/dependents, you will see a list of 0 star. imagine you are a new comer of react, and want to see some real use case, it hard to find use https://github.com/facebook/react/network/dependents. but you can use useful-dependents to filter 0 stars, and load multi-pages at once to avoid click "next" button again and again.

that is just why i made useful-dependents, and I think it is helpful

**Comment by fregante** [comment]
Showing a handful of 1-star repos still isn't useful. You can blame GitHub for offering poor UI and API, but that doesn't justify the existence of a tool that makes it "slightly better but still not useful"

**Pull request closed without merging**
