### PR TITLE
Add `isPublicRepo`

### PR DESCRIPTION
**Pull request by kidonng**
To be used in Refined GitHub (I think there may be several features could benefit from this)

I wonder why we didn't have this (until now)

Test URL: here

### CODE REVIEW

**Comment by kidonng** [comment]
Hmm, so we have a Netlify bot now, <sub>but I prefer Vercel</sub> `:thinking:`

**Comment by fregante** [comment]
Vercel doesn’t prefer us so I had to switch. Organizations aren’t free on Vercel and even after contacting them they refused to allow it. So Netlify is just as good.

**Review by fregante — APPROVED** [review]
Same applies: https://github.com/refined-github/github-url-detection/pull/141#issuecomment-1194963289

Merge only if ready to be used

**Comment by fregante** [comment]
Meta: I think I disabled Netlify’s comments. The preview URLs are still available in the checks list

**Comment by kidonng** [comment]
Given updates on #5853 I'm merging this.

**Pull request merged**
